version: '2'
services:
    jhipstertestapplication-app:
        image: jhipstertestapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstertestapplication-mysql:3306/jhipstertestapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    jhipstertestapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstertestapplication-mysql
